#ifndef PARALLEL_AC_AUTOMATION_PARALLELACAUTOMATION_H
#define PARALLEL_AC_AUTOMATION_PARALLELACAUTOMATION_H


class ParallelAcAutomation {

};


#endif //PARALLEL_AC_AUTOMATION_PARALLELACAUTOMATION_H
